DROP PROCEDURE IF EXISTS proc1;
DROP PROCEDURE IF EXISTS proc2;
DROP PROCEDURE IF EXISTS proc3;

-- Variable IN
DELIMITER //
CREATE PROCEDURE proc1(IN p INT) SET @x = p
//

-- Variable OUT
DELIMITER //
CREATE PROCEDURE proc2(OUT p INT) SET p = -5
//

-- Variable INOUT
DELIMITER //
CREATE PROCEDURE proc3(INOUT p INT) SET p = p-5
//